plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-berry.cjs

packageExtensions:
  "@tailwindcss/typography@^0.3.1":
    dependencies:
      lodash: "^4"
  babel-plugin-jsx-dom-expressions@^0.24:
    peerDependencies:
      "@babel/core": "^7.0.0"
  babel-preset-solid@^0.23:
    peerDependencies:
      "@babel/core": "^7.0.0"
